name: bsa
channels:
  - https://conda.ovito.org
  - conda-forge
  - defaults
dependencies:
  - dask=2023.11.0
  - freud=2.13.2
  - ipython=8.20.0
  - matplotlib=3.8.2
  - mdanalysis=2.6.1
  - numpy=1.26.3
  - ovito=3.10.1
  - pandas=2.2.0
  - pip=23.3.2
  - python=3.11.6
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - signac=2.1.0
  - signac-dashboard=0.6.1
  - signac-flow=0.26.1
  - spyder=5.5.0
  - pip:
      - atooms==3.20.1
      - atooms-pp==3.4.0
      - pyprojroot==0.3.0
      - pytest==8.0.0