name: Build and Deploy Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: beadspring-docs
          environment-file: environment.yml
          python-version: 3.11

      - name: Check environment
        run: |
          conda info
          conda list

      - name: Build documentation
        shell: bash -l {0}
        working-directory: docs
        run: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html