name: Build and Deploy Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: bsa
          auto-activate-base: false

      - name: Install dependencies and build docs
        run:
          pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints
      
      - name: Install package in editable mode
        shell: bash -l {0}
        run: |
          pip install -e .
          cd docs
          make clean html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          allow_empty_commit: true
